public class BiodataDaffa {
    public static void main(String[] args) {
        System.out.println("---------------------------------------------------------");
        System.out.println("-- Data Mahasiswa Jurusan Teknologi Informasi POLINEMA --");
        System.out.println("---------------------------------------------------------");
        System.out.println("Nama    : Raihan Daffa Izzuddin");
        System.out.println("NIM     : 244107020113");
        System.out.println("Kelas   : 1D");
        System.out.println("No Absen: 25");
        System.out.println("Prodi   : D-IV Teknik Informatika");
        System.out.println("Alamat  : Samaan, Klojen, Kota Malang");
        System.out.println("No HP   : 081292655720");
        System.out.println("Hobi    : Berenang");
    }
}